# Generated by Django 3.1.7 on 2021-05-24 12:50

from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilecontent',
            name='file',
            field=models.FileField(upload_to=page.models.user_directory_path),
        ),
    ]
