# Generated by Django 3.1.7 on 2021-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210524_1850'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pages',
            field=models.ManyToManyField(related_name='Module_Page', to='page.Page'),
        ),
    ]
