# Generated by Django 3.1.7 on 2021-05-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('module', '0002_module_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quizzes',
            field=models.ManyToManyField(related_name='Module_Quiz', to='quiz.Quizzes'),
        ),
    ]
