# Generated by Django 3.1.7 on 2021-05-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='article', max_length=100, verbose_name='Icon'),
        ),
    ]
