# Generated by Django 3.1.7 on 2021-05-21 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0003_course_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled',
            field=models.ManyToManyField(related_name='Enrolled_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
