# Generated by Django 3.1.7 on 2021-05-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('classroom', '0004_auto_20210521_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(related_name='Course_Modules', to='module.Module'),
        ),
    ]
