# Generated by Django 3.1.7 on 2021-05-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeopleList',
        ),
    ]
